# Makefile

.PYHONY: all clean

all: step0.out step1.out step2.out step3.out step4.out step5.out step6.out step7.out step8.out step9.out step10.out

step0.out: step0.cpp
	g++ -std=c++20 -o step0.out step0.cpp

step1.out: step1.cpp
	g++ -std=c++20 -o step1.out step1.cpp

step2.out: step2.cpp
	g++ -std=c++20 -o step2.out step2.cpp

step3.out: step3.cpp
	g++ -std=c++20 -o step3.out step3.cpp

step4.out: step4.cpp
	g++ -std=c++20 -o step4.out step4.cpp

step5.out: step5.cpp
	g++ -std=c++20 -o step5.out step5.cpp

step6.out: step6.cpp
	g++ -std=c++20 -o step6.out step6.cpp

step7.out: step7.cpp
	g++ -std=c++20 -o step7.out step7.cpp

step8.out: step8.cpp
	g++ -std=c++20 -o step8.out step8.cpp

step9.out: step9.cpp
	g++ -std=c++20 -o step9.out step9.cpp

step10.out: step10.cpp
	g++ -std=c++20 -o step10.out step10.cpp

clean:
	rm -f *.out
